import { asciiBytes, utf8Bytes } from "@native-sdk/core";
import type { DictationWorkflow, Model } from "./core.ts";

export function defaultModel(): Model {
  return {
    durationLimitReached: false,
    workflow: { kind: "booting" },
    sessionId: 0 / 1,
    generation: 0 / 1,
    pressedAtMs: 0 / 1,
    lastQuickReleaseAtMs: 0 / 1,
    capturedFrames: 0 / 1,
    sessionSourceToken: asciiBytes(""),
    workflowMessage: asciiBytes(""),
    hasImmediateResult: false,
    immediateResultKind: "shown",
    immediateResultMessage: asciiBytes(""),
    permissionsLoaded: false,
    modelsLoaded: false,
    microphonePermission: false,
    accessibilityPermission: false,
    inputMonitoringPermission: false,
    modelReady: false,
    selectedModelKey: 0 / 1,
    onboardingComplete: false,
    limitedModeAccepted: false,
    hotkeyConfirmed: false,
    doubleTapEnabled: true,
    doubleTapWindowMs: 300 / 1,
    minimumHoldMs: 300 / 1,
    overlayEnabled: true,
    pasteAutomatically: true,
    launchAtLogin: false,
    ambientDetail: utf8Bytes("Checking permissions and local model readiness…"),
    page: "settings",
    platformLoaded: false,
    platformSupported: false,
    platformArchitecture: asciiBytes(""),
    platformOSVersion: asciiBytes(""),
    platformMessage: utf8Bytes("Checking Mac compatibility…"),
    onboardingStep: 0 / 1,
    hotkeyChoice: "command_shift",
    hotkeyConfig: asciiBytes("key=-1;command=1;shift=1;option=0;control=0;fn=0"),
    hotkeyDisplay: utf8Bytes("Command + Shift"),
    hotkeyCandidateConfig: asciiBytes(""),
    hotkeyCandidateDisplay: asciiBytes(""),
    hotkeyCandidateWarning: asciiBytes(""),
    hotkeyCandidateValid: false,
    hotkeyPracticed: false,
    modelDownloadState: "idle",
    modelDownloadUserCancelled: false,
    modelDownloadedBytes: 0 / 1,
    modelTotalBytes: 0 / 1,
    modelDownloadedBytesLabel: asciiBytes("0"),
    modelTotalBytesLabel: asciiBytes("0"),
    modelDownloadMessage: asciiBytes(""),
    hotkeyCaptureActive: false,
    managedModelBytes: 0 / 1,
    modelCount: 0 / 1,
    activeModelName: asciiBytes(""),
    modelRows: [],
    hfResolved: false,
    hfResolvedAllowlisted: false,
    hfResolvedIdentifier: asciiBytes(""),
    hfResolvedRevision: asciiBytes(""),
    hfResolvedArtifact: asciiBytes(""),
    hfResolvedSize: asciiBytes(""),
    hfResolvedLicense: asciiBytes(""),
    hfResolvedProvider: asciiBytes(""),
    hfResolvedAttribution: asciiBytes(""),
    hfResolvedConfirmed: false,
    activeModelSource: asciiBytes(""),
    activeModelLicense: asciiBytes(""),
    activeModelLanguages: asciiBytes(""),
    activeModelBytes: 0 / 1,
    hfDraft: asciiBytes(""),
    hfSourceConfirmed: false,
    activeModelSizeText: asciiBytes(""),
    managedModelSizeText: asciiBytes(""),
    diagnosticsExported: false,
    diagnostics: utf8Bytes("Diagnostics have not been collected."),
    microphoneName: utf8Bytes("System default microphone"),
    microphoneDetail: utf8Bytes("Checking input format…"),
    meterLevel: "quiet",
    elapsedMilliseconds: 0 / 1,
    loginStatus: "checking",
    appearanceOverride: "system",
    systemColorScheme: "light",
    reduceMotion: false,
    automationSceneActive: false,
    highContrast: false,
    automationOverlayPreview: false,
  };
}

export function readiness(model: Model): DictationWorkflow {
  if (!model.platformLoaded || !model.permissionsLoaded || !model.modelsLoaded) return { kind: "booting" };
  if (!model.platformSupported) return { kind: "not_ready" };
  if (!model.microphonePermission) return { kind: "not_ready" };

  if (!model.inputMonitoringPermission && !model.limitedModeAccepted) return { kind: "not_ready" };
  if (!model.hotkeyConfirmed && !model.limitedModeAccepted) return { kind: "not_ready" };
  if (!model.modelReady || model.selectedModelKey === 0) return { kind: "not_ready" };
  if (!model.onboardingComplete) return { kind: "not_ready" };
  return { kind: "ready", modelKey: model.selectedModelKey };
}
export function durableModel(model: Model): Model {
  return {
    ...model,
    durationLimitReached: false,
    workflow: { kind: "booting" },
    sessionId: 0 / 1,
    generation: 0 / 1,
    pressedAtMs: 0 / 1,
    lastQuickReleaseAtMs: 0 / 1,
    capturedFrames: 0 / 1,
    sessionSourceToken: asciiBytes(""),
    workflowMessage: asciiBytes(""),
    hasImmediateResult: false,
    immediateResultKind: "shown",
    immediateResultMessage: asciiBytes(""),
    permissionsLoaded: false,
    modelsLoaded: false,
    microphonePermission: false,
    accessibilityPermission: false,
    inputMonitoringPermission: false,
    modelReady: false,
    ambientDetail: asciiBytes(""),
    modelDownloadState: "idle",
    modelDownloadUserCancelled: false,
    modelDownloadedBytes: 0 / 1,
    modelTotalBytes: 0 / 1,
    modelDownloadMessage: asciiBytes(""),
    managedModelBytes: 0 / 1,
    modelDownloadedBytesLabel: asciiBytes("0"),
    modelTotalBytesLabel: asciiBytes("0"),
    modelCount: 0 / 1,
    activeModelName: asciiBytes(""),
    activeModelSource: asciiBytes(""),
    hotkeyCandidateConfig: asciiBytes(""),
    hotkeyCandidateDisplay: asciiBytes(""),
    hotkeyCandidateWarning: asciiBytes(""),
    hotkeyCandidateValid: false,
    modelRows: [],
    activeModelLicense: asciiBytes(""),
    activeModelLanguages: asciiBytes(""),
    activeModelBytes: 0 / 1,
    hfDraft: asciiBytes(""),
    diagnosticsExported: false,
    hotkeyCaptureActive: false,
    hfSourceConfirmed: false,
    activeModelSizeText: asciiBytes(""),
    managedModelSizeText: asciiBytes(""),
    diagnostics: utf8Bytes("Diagnostics have not been collected."),
    microphoneName: utf8Bytes("System default microphone"),
    microphoneDetail: utf8Bytes("Checking input format…"),
    meterLevel: "quiet",
    elapsedMilliseconds: 0 / 1,
    loginStatus: "checking",
    appearanceOverride: "system",
    systemColorScheme: "light",
    reduceMotion: false,
    automationSceneActive: false,
    hfResolved: false,
    hfResolvedAllowlisted: false,
    hfResolvedIdentifier: asciiBytes(""),
    hfResolvedRevision: asciiBytes(""),
    hfResolvedArtifact: asciiBytes(""),
    hfResolvedSize: asciiBytes(""),
    hfResolvedLicense: asciiBytes(""),
    hfResolvedProvider: asciiBytes(""),
    hfResolvedAttribution: asciiBytes(""),
    hfResolvedConfirmed: false,
    highContrast: false,
    automationOverlayPreview: false,
  };
}
